// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ComponentList: typeof import('./../src/components/left-aside/ComponentList.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    LeftAside: typeof import('./../src/components/left-aside/index.vue')['default']
    Main: typeof import('./../src/components/main/index.vue')['default']
    PageWrapper: typeof import('./../src/components/main/PageWrapper.vue')['default']
    RightAside: typeof import('./../src/components/right-aside/index.vue')['default']
    SimulatorEditor: typeof import('./../src/components/main/SimulatorEditor.vue')['default']
    Try: typeof import('./../src/components/main/Try.vue')['default']
  }
}

export { }
