// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    LeftAside: typeof import('./../src/components/left-aside/index.vue')['default']
    Main: typeof import('./../src/components/main/index.vue')['default']
    RightAside: typeof import('./../src/components/right-aside/index.vue')['default']
    SimulatorEditor: typeof import('./../src/components/main/SimulatorEditor.vue')['default']
  }
}

export { }
